workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      java: 17

    scripts:
      - name: Grant execute permission
        script: chmod +x ./gradlew || true

      - name: Build APK
        script: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug
          else
            echo "Gradle wrapper not found"
            exit 1
          fi

    artifacts:
      - app/build/outputs/**/*.apk
